### ISSUE TITLE
Feature request: Support ZIP

### ISSUE THREAD

**Issue by paambaati** [101arrowz/fflate#1]
Supporting creating and extracting ZIP files would be very useful, especially for real-world use cases like zipping multiple uploads into one on the client-side and then uploading to a pre-signed S3 URL.

**Comment by 101arrowz** [comment]
I'll get to this in a few days, after I add tests. Could you give a general sense of the API you'd like to use?

**Comment by paambaati** [comment]
Awesome. I’d borrow the APIs (`.zip()` and `.unzip()`) from JSZip.

For an initial version, it could simply support `File` objects, with Base64 files coming later.

I’d also love to be able to tweak the compression level. I’d imagine for people who just want to store quickly and don’t care for compression, level `0` would be useful, not to mention fast and lightweight too.

**Comment by 101arrowz** [comment]
Quick update, I'm working on built-in `Worker` support as a prerequisite to this because adding ZIP support but not compressing in parallel just feels wrong... it seems that nobody else is really making isomorphic workers, so I had to write a lot of extra code to make it work. Bundle size will probably increase a to around 13kB for non-ESM users, but I think the performance benefits are worth it.

**Comment by paambaati** [comment]
@101arrowz That’s fantastic news! Would that mean it would take of registering/unregistering workers too? Or will there be specific methods to run the operations inside a `Worker`?

**Comment by 101arrowz** [comment]
The entire lifecycle (creation, passing data, and destruction) will be done automatically. A new worker is created and destroyed each call. I'm doing it inline, so all bundlers should still work, and IE10+ is still supported. Honestly, I'm surprised nobody else has done this yet.

**Comment by paambaati** [comment]
Sounds great. Would it also fallback to the main thread if the browser doesn’t support workers?

**Comment by 101arrowz** [comment]
No, it does not fall back, but I'm exporting both a synchronous and asynchronous (Worker) API, so it shouldn't matter if you're trying to support one of the very few browsers that supports Typed Arrays but not Web Workers (mainly Opera Mini).

**Comment by 101arrowz** [comment]
I've finished adding Worker support, now I'm adding ZIP APIs.

**Comment by paambaati** [comment]
![8F275738-7809-4064-8FCE-10B0802FA401](https://user-images.githubusercontent.com/5381764/94371891-72fd2380-0117-11eb-81f7-ebdd9c73f723.gif)

**Comment by 101arrowz** [comment]
I just added ZIP support. The parallelized (asynchronous) version is extremely fast, even more so than many standalone C-based tools. Thanks for the feature request!
