### ISSUE TITLE
Gzip corruption issue

### ISSUE THREAD

**Issue by sHoskens** [101arrowz/fflate#10]
I've encountered a few corrupted files after using gzip with fflate, both the async and sync versions. Results appear to be deterministic, always occuring on the same files on different machines. I've made sure that the issue is somewhere in fflate. (removed all other variables and side-by-side with pako. Pako did not produce any corruption)

Issue only occurs on a small subset of files, less then 10% of what we use. It's always rather large files, in the >200MB range. I tried changing the compression level, and this gave some good initial results. However, it appears that another compression level just causes corruption in completely different files.

I've currently reverted back to pako, but would like to continue using fflate once this is resolved. If you want, I can send you example files that get corrupted to help with debugging this. (These are large medical files stripped of identifiable data, yet still to sensitive to just upload publically ;) )

**Comment by 101arrowz** [comment]
Please do send them to me, it would be very helpful to investigate.

**Comment by 101arrowz** [comment]
I tried the program on a variety of standard (10MB), large (200MB), and massive (1GB) files, but `fflate` seems to handle them fine. It's certainly a specific bug caused by your input, so please send them to me as soon as you can. Thanks for the report!

**Comment by sHoskens** [comment]
I've only tested in gzip so far, I'll try a test with deflate tomorrow!

**Comment by 101arrowz** [comment]
I received the files, and will test in a few hours when I have time. Thanks for your help!

**Comment by 101arrowz** [comment]
So my findings so far:

I can confirm that there's an issue for one of the files you sent, but the other three work fine from my tests.
The file that doesn't work breaks at byte 246600103 of 252909668 due to a literal value 218. I'm not exactly sure why and am debugging now.
Deflate and GZIP both have the bug, so it's a core algorithm flaw, and not a CRC issue.

**Comment by sHoskens** [comment]
The other three currently work fine as well on my tests. I could replicate it just yesterday though, but perhaps this was an unrelated mistake in between the switching of libraries/versions.

For the file that gets corrupted: It gets zipped correctly when I change the level to 4.

**Comment by 101arrowz** [comment]
I've discovered the bug. It was an incredibly rare edge case of integer overflow in a Uint8Array; switching to Uint16Array did the trick. I would probably never have found it without your help, so thank you :)

I will push the updates soon.

**Comment by sHoskens** [comment]
Ah, that's great to hear! Very curious towards the fix, looking forward to the commit!

**Comment by 101arrowz** [comment]
[This diff](https://github.com/101arrowz/fflate/commit/61fa99ab81a603fe1a32492f5068ff6511d86881#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L71-R71) fixed the issue for me. Could you try the package on your files now? It seems to work for me, but I can't be sure everything's fixed until you verify.

**Comment by sHoskens** [comment]
Great, that seems to have fixed it! Thanks a lot. We're going to be using this quite a lot on a diverse range of files in the upcoming weeks, so I will keep you posted if I ever encounter something like this. Thanks for the swift reply and resolution!

For the files, just deleting them is okay!
