### ISSUE TITLE
Crashing in Ios.

### ISSUE THREAD

**Issue by ktjd123** [101arrowz/fflate#11]
compressing in ios is crashing. I didn't check in android.

the code I used is

```ts
    const data = zipSync(tozip, { level: 0, mem: 0 });
    saveAs(new Blob([data as Uint8Array]), `${this.title}.zip`);
```

the result zip file made with pc is about 200~300mb and including about 80 jpg photos.

Thank you, I always appreciate your work.

**Comment by ktjd123** [comment]
It's working just fine now. I can't find the diff inside code. weird.

**Comment by ktjd123** [comment]
It' happening occasionally with same code. can't find what's wrong.

**Comment by 101arrowz** [comment]
Could you send me an example of the files you are zipping? That makes it easier to debug. Model number and version number of the iOS device and browser would also be helpful.

**Comment by ktjd123** [comment]
Hi, Can I get email of you please? since it's huge file.

Software version is 14.1
Model number is MWC52KH/A
Browser is safari

**Comment by 101arrowz** [comment]
Yes, you can send the files to the [email listed on my profile](mailto:arjunbarrett@gmail.com).

On the iOS simulator, the model number you sent works fine for some moderately sized files. I'll need to look into it further to diagnose the issue.

Also, you might want to check if JSZip crashes as well. If it does, then it may not be an issue with the library but rather the environment.

**Comment by ktjd123** [comment]
JSZip doesn't crash. sent email! . Thank you

I'm using next.js

**Comment by 101arrowz** [comment]
I received the files and have run tests both on a simulated iPhone with the exact specifications you gave and a real iPhone 11 Pro 256GB. Neither hung during zipping. Would you be able to share the code surrounding the call? It's possible that you're using the result in a way that's too computationally difficult for the browser to handle.

**Comment by ktjd123** [comment]
I don't see any problem now. Weird... I will reopen the issue when this happens again.

I used debug menu but when the page crashes debugger console doesn't work anymore so I can't see the error.

Thank you for helping. !

**Comment by ktjd123** [comment]
Hi, I'm having this issue again in mem:1 setting to mem:12 setting. Can I send you zip file for test?

**Comment by 101arrowz** [comment]
`mem` cannot have an impact with level 0, it's entirely ignored. If you're using non-level 0, please send the files again and I'll try to debug.

**Comment by ktjd123** [comment]
Oh Thank you, I'll recheck and send files. It seems to be with ios safari download limit not fflate. Thank you. Sorry for bothering you.
