### ISSUE TITLE
broken AMD loading 

### ISSUE THREAD

**Issue by decibelko** [101arrowz/fflate#110]
Hi, AMD loading seems to be broken when using requirejs.
I'm trying to load module via `require()` call.

This might fix it:
in scripts\buildUMD.ts
change 
`define(['fflate',f])`
->
`define([],f)` or simply `define(f)` because of no dependencies

Great little lib! Many thanks for it

**Comment by 101arrowz** [comment]
Will fix in the next release, I've never used AMD so I didn't know this. Thanks for the bug report!

**Comment by 101arrowz** [comment]
Fixed in v0.7.2.
