### ISSUE TITLE
Fix size regressions

### ISSUE THREAD

**Issue by 101arrowz** [101arrowz/fflate#115]
A key focus of this package has always been small bundle size but I've noticed that newer versions have had larger than expected sizes, even with tree-shaking. I'm going to try to reduce bundle size dramatically to actually fulfill the 8kB claim by fixing issues preventing proper tree-shaking.

**Comment by 101arrowz** [comment]
There's a bug in Parcel causing larger size than expected: https://github.com/parcel-bundler/parcel/issues/7481. I'll check for issues with Webpack soon.

**Comment by lunabunn** [comment]
The issue upstream was resolved 3 days ago 🎉

**Comment by 101arrowz** [comment]
Thanks for letting me know, I'll close this after I verify any issues w/ Webpack.

**Comment by 101arrowz** [comment]
I think the size regressions are mostly fixed. If there are any future issues I encounter I will reopen this issue.
