### ISSUE TITLE
Create zip with empty directory

### ISSUE THREAD

**Issue by ryanlin1986** [101arrowz/fflate#118]
For example, I just want to create empty directory named test, the following code does not work.

```js
zipSync({
  test: {}
})
```

**Comment by 101arrowz** [comment]
This is probably something that should be supported for consistency, but you can do this instead:

```js
zipSync({
  'test/': new Uint8Array(0)
})
```

**Comment by 101arrowz** [comment]
Added support for the original syntax in v0.7.3. Thanks for the feature request!
