### ISSUE TITLE
Could not resolve import "worker_threads" when trying to use in web

### ISSUE THREAD

**Issue by maxevilmind** [101arrowz/fflate#12]
Hi everyone,
I am trying to use the library as an ESM module like that:
`import * as fflate from 'fflate';`
But I am getting `Error: Could not resolve import "worker_threads" in "../../../node_modules/fflate/esm/node-worker.js".`
In `esm/index.js` I see the following line `import wk from './node-worker';` and if I change it to `import wk from './worker';` it works fine.

As I understand it tries to run node version worker in web for some reason. Does it miss some sort of condition to import proper worker?

I really need this so I am ready to work out a PR for that.

**Comment by 101arrowz** [comment]
What bundler are you using? I rely on the `"browser"` key of `package.json` to replace the import in the browser.

**Comment by maxevilmind** [comment]
@101arrowz we don't have any bundler 🙈 
We have a build-less open-wc setup (more on that https://modern-web.dev/guides/going-buildless/es-modules/#commonjs-modules). That's pretty much what brought us to use fflate as it provides ESM exports and other similar libraries are `common js`. I am not sure if it is somehow possible to utilize this key while using no bundler.

**Comment by 101arrowz** [comment]
If that's the case, I will change the build script to add a version that supports true ESM. Is there nothing in that guide that allows custom module resolution?

**Comment by maxevilmind** [comment]
@101arrowz wow that would be really amazing to get the `true ESM` version.
`Is there nothing in that guide that allows custom module resolution?`
I think unless I write my own tool for it - there is no way...

**Comment by 101arrowz** [comment]
@maxevilmind I've pushed v0.3.6 with commit 214ec2f645b3195390f95abd0c0925609e28d9bd. Check the README for instructions on importing and let me know if they work. Thanks for the feature request!

**Comment by maxevilmind** [comment]
@101arrowz amazing! thank you for pushing it quickly!
I will test it out today

**Comment by 101arrowz** [comment]
Did it end up working for you?

**Comment by maxevilmind** [comment]
yep, import works perfectly now
thank you for adding the changes!

**Comment by 101arrowz** [comment]
No idea how useful this is for you at this point @maxevilmind, but you probably would have been able to get the package working like this:
```
web-dev-server --config config.wds.mjs
```
In `config.wds.mjs`:
```
export default {
  nodeResolve: {
    "browser": true
  }
}
```
Obviously I'm not going to revert the package to before this bugfix, just thought it may be useful to know.
