### ISSUE TITLE
Missing header when read with 7Zip with async api

### ISSUE THREAD

**Issue by Plawn** [101arrowz/fflate#126]
**How to reproduce**

Use the async api, with Zip and ZipDeflate, .end() and .terminate() write the chunks to a blob and save the file.

The file will properly be opened by windows explorer and 7Zip but 7Zip will complain about missing headers.
The files can be properly opened and are not corrupted.

**Comment by 101arrowz** [comment]
Probably the same as #78. Last time I tried to fix it I wasn't able to do so without adding a ton of extra complexity but I'll look into it again.

**Comment by 101arrowz** [comment]
Think I've managed to fix this, will update in next release.

**Comment by 101arrowz** [comment]
Fixed in v0.7.4.
