### ISSUE TITLE
Migration from jszip to fflate

### ISSUE THREAD

**Issue by jadfls** [101arrowz/fflate#14]
Hi,

thank you for your comment at https://github.com/Stuk/jszip/issues/721#issuecomment-722680866

I am trying to review fflate if it would meet my requirements. However, the documentation is not very good and I cannot get my compressed zip file unzipped. Can you help out here?

My code from jszip
```
//zippedData is binary String
        let foundXml = "";
        try {
            var JSZip = require("jszip");
            var zip = new JSZip();
        
            const zipped = await zip.loadAsync(zippedData);
            foundXml = await zipped.file("data.xml").async("string");
        } catch(err) {
            console.log(err);
        }
```

What i tried in fflate
```
            try {
                let buffer = fflate.strToU8(zippedData, true);
                let unzipped = fflate.unzipSync(buffer);
                console.log("unzipped", unzipped);                     //-> this returns {"data.xml": []}
                console.log("unzipped", unzipped["data.xml"]);                    //-> this returns []
            } catch(err) {
                console.log(err);
            }
```
So I get the file unzipped but the data.xml inside is empty.

**Comment by 101arrowz** [comment]
As I mentioned, all of the functions return binary data in the form of `Uint8Array`. If you want a string, you can convert a buffer to string with `strToU8`.

```js
try {
    let buffer = fflate.strToU8(zippedData, true);
    let unzipped = fflate.unzipSync(buffer);
    console.log("unzipped", unzipped);
    // Logs a UTF-8 string with the data in the ZIP
    console.log("unzipped", fflate.strToU8(unzipped["data.xml"]));
} catch(err) {
    console.log(err);
 }

**Comment by 101arrowz** [comment]
@jadfls Did that work for you?

**Comment by jadfls** [comment]
@101arrowz Thanks for the feedback. But, unfortunately it did not work.

1. with your 2nd example I get `[TypeError: cb is not a function. (In 'cb(null, files)', 'cb' is an instance of Object)]`. I had to remove `{ consume: true }` to get it to work. But the xml data is still empty
2. As said, `unzipped` is `{"data.xml": []}`. That means it actually finds the xml file inside the zip. But the contents of the file is empty. I don't think `fflate.strFromU8(...)`around the empty array will change that.

It would be nice to have a example flow where it reads a zip file and extracts the contents of the files inside the zip.

**Comment by 101arrowz** [comment]
1. I'll fix that, that's definitely a bug.
2. Are you certain that it's an empty array? Uint8Arrays sometimes don't show their data in `console.log`, just try using `strToU8`. If that still doesn't work, please send me the ZIP file (email or link works).

**Comment by 101arrowz** [comment]
Just to give a more comprehensive example:

```js
import { unzip as fflUnzip, strFromU8, strToU8 } from 'fflate';
// If on Node.js, use util.promisify
const promisify = func => {
    return (...args) => {
        return new Promise((resolve, reject) => {
            func.call(null, ...args, (err, res) => {
                if (err) reject(err);
                else resolve(res);
            });
        });
    }
}
const unzip = promisify(fflUnzip);

// later, in an async function:
try {
    const buffer = strToU8(binstring, true);
    const out = await unzip(buffer);
    const dataXml = strFromU8(out['data.xml']);
    console.log(dataXml); // your XML is printed
} catch(e) {
    console.error(e);
}
```

**Comment by 101arrowz** [comment]
You may also want to take a look at this sandbox: https://codesandbox.io/s/hungry-wave-l8sn8?file=/src/index.js

**Comment by jadfls** [comment]
@101arrowz  thanks for the help. At this point, it is probably best for you to check the zip file. There must be something special about it. Unfortunately, the zip content is confidential, so I will send you via email if you don't mind.

**Comment by 101arrowz** [comment]
Thanks, I've received the email and am debugging now. I already found a way to resolve the issue and get the 500 kB XML output, but it drastically reduces performance; looking for an alternate solution now.

**Comment by 101arrowz** [comment]
@jadfls Check v0.4.0 on NPM, it should have fixed the issue.

**Comment by jadfls** [comment]
This works now. Thank you very much.

**Comment by OPSnake** [comment]
Hi,

This works for small zip file but not for large blob file (> 2Go) I don't find methode for picking 1 file quickly without uncompress all zip.

Can you help out here?

```javascript
import { unzip as fflUnzip, strFromU8, strToU8 } from 'fflate';
// If on Node.js, use util.promisify
const promisify = func => {
    return (...args) => {
        return new Promise((resolve, reject) => {
            func.call(null, ...args, (err, res) => {
                if (err) reject(err);
                else resolve(res);
            });
        });
    }
}
const unzip = promisify(fflUnzip);

// later, in an async function:
try {
   // zipFile is a blob file
    const buffer = new Uint8Array(await zipFile.arrayBuffer());
    const out = await unzip(buffer);
    const dataJson = strFromU8(out['data.json']);
    console.log(dataJson ); 
} catch(e) {
    console.error(e);
}
```

**Comment by 101arrowz** [comment]
If you have a massive file, don't use the convenience `unzip` method. Instead, it's far better to use the streaming system, which allows you to unzip data with low memory usage.

```js
import { Unzip, AsyncUnzipInflate, DecodeUTF8 } from 'fflate';

const data = await new Promise(async (resolve, reject) => {
  // Stop pushing data when this is true
  let foundDataJSON = false;
  const uz = new Unzip(file => {
    if (file.name == 'data.json') {
      // This JSON string grows bigger over time
      let json = '';
      const utf8decoder = new DecodeUTF8((str, final) => {
        json += str;
        if (final) {
          // Finished getting the data; now we can stop pushing
          foundDataJSON = true;
          resolve(JSON.parse(json));
        }
      });
      file.ondata = (err, dat, final) => {
        if (err) {
          reject(err);
          return;
        }
        try {
          // Convert binary chunks into strings
          utf8decoder.push(dat, final);
        } catch (err) {
          reject(err);
          file.terminate();
        }
      }
      // start decompression
      file.start();
    }
  });
  uz.register(AsyncUnzipInflate);
  const fileStream = zipFile.stream();
  const reader = fileStream.getReader();
  // Automatically stops after we find data.json
  while (!foundDataJSON) {
    const { done, value } = await reader.read();
    if (done) break;
    uz.push(value);
  }
});
```

I know this looks like a lot of code to do something simple, but I promise you this will be more memory efficient and much faster than doing it normally. All it does is incrementally push data to the unzipper and only decompress if it's `data.json`.

As you can see, I called `zipFile.stream()`, but if you can get a `ReadableStream` without storing the data in a blob first (e.g. if this is a `File` object), you'll save 2GB of memory.

**Comment by OPSnake** [comment]
This works now. Thank you very much.

I Have another issue when unzip all files. 
In callback ondata in file, i have an exception on 2 files over 3691: "Error: unexpected EOF at inflt".

If you want, i will be sending my zip file with this error.

```javascript
  const uz = new Unzip(async file => {
      let relativePath = file.name;
      let indexOfSlash = relativePath.lastIndexOf('/');
      if (indexOfSlash > 0) {
          let directoryPath = relativePath.slice(0, indexOfSlash);
          await FileStorageHelper.createDirectoryAsync(destination, directoryPath);
      }
    
      let fileOnDisk = await FileStorageHelper.createFileAsync(destination, relativePath);
      let readable = new ReadableStream({
          start(controller: ReadableStreamDefaultController<Uint8Array>) {
              file.ondata = (err, chunk, final) => {
                  if (err) { 
                      controller.error(err); 
                  }
    
                  try {
                      controller.enqueue(chunk);
                      if (final) controller.close();
                  } catch (err) {
                      file.terminate();
                      reject(err);
                  }
              }
          }
    
      });
    
      file.start();
      await FileStorageHelper.writeFileAsync(fileOnDisk, readable);
  });
```

**Comment by 101arrowz** [comment]
Yes, please send me the file. I will see if it is an error that can be fixed.

**Comment by 101arrowz** [comment]
Hi @OPSnake, this is actually the same error as #66. I'm trying to see if there's a workaround, but for now you can use `fflate.unzip`.
