### ISSUE TITLE
Per file compression options in ZIP don't work as described

### ISSUE THREAD

**Issue by anongit** [101arrowz/fflate#15]
In the demo:
```typescript
    // With fflate, we can choose which files we want to compress
    zipObj[file.name] = [buf, {
      level: ALREADY_COMPRESSED.indexOf(ext) == -1 ? 6 : 0
    }];
```
Changing `6` to `1` or to any other number except `0` doesn't affect the execution time or file size.
You have to change it here:
```typescript
 if (!--left) {
      fflate.zip(zipObj, {
        // If you want to control options for every file, you can do so here
        // They are merged with the per-file options (if they exist)
        // mem: 9
        level: 1
      }, function(err, out) {
```
I see in the code, that you do merge them like it says in the comment, but in the following line instead of using the merged result you pass the default options:
https://github.com/101arrowz/fflate/blob/ffbb65cec39a1b09fa8ae3f687ea2349e472cf18/src/index.ts#L2149

**Comment by 101arrowz** [comment]
Thanks for the bug report! That's quite a silly mistake, I'll fix that right now.

**Comment by 101arrowz** [comment]
Check v0.4.1 on NPM and the updated browser demo, the issue should be resolved. Thanks for taking the time to diagnose the issue as well, I appreciate it a lot!
