### ISSUE TITLE
zlibSync compressed size is larger than pako

### ISSUE THREAD

**Issue by yisibl** [101arrowz/fflate#158]
I am trying to migrate ttf2woff from pako to fflate and found that the file size has become bigger.

You can run `node example/index.js` from this repository https://github.com/yisibl/ttf2woff-fflate/tree/master/fixtures

```bash
File Size
oldWoff(pako) : 9536
newWoff(fflate): 9592
```

**Comment by 101arrowz** [comment]
For certain types of data `fflate` is slightly less effective than Pako, but it should rarely be much worse in compression ratio and will almost never be slower. A difference of about 1% as you're seeing here is not unusual.

**Comment by yisibl** [comment]
Thanks, for example for font files, is there a possibility to improve fflate?

**Comment by 101arrowz** [comment]
It is possible but unlikely. Algorithmically, `fflate` is pretty much complete.

**Comment by yisibl** [comment]
Thanks!
