### ISSUE TITLE
gunzipSync return array with 143.000.000 length

### ISSUE THREAD

**Issue by zalenskiSofteq** [101arrowz/fflate#161]
**How to reproduce**

call gunzipSync with Uint8Array [31, 139, 8] as the argument

**The problem**

argument with 3 bytes breaks the library

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/63463140/220128416-e9ce3529-f690-43a2-a6cf-fd131c111829.png">

**Comment by 101arrowz** [comment]
This should throw an error, will fix for the next version.

**Comment by 101arrowz** [comment]
Fixed in v0.8.0.
