### ISSUE TITLE
Deflate/Inflate does not work with zlib/gzip c++

### ISSUE THREAD

**Issue by jammerxd** [101arrowz/fflate#171]
Zlib and Gzip deflate results do not match zlib/gzip c/c++ implementation thus giving Z_DATA_ERROR when trying to inflate in c/c++ OR on pako's own module.

**Comment by 101arrowz** [comment]
Could you send some code I can use to reproduce this? As far as I know the streams work as expected.

**Comment by 101arrowz** [comment]
fflate's `deflateSync` and `inflateSync` actually correspond to pako's `deflateRaw` and `inflateRaw`. I probably should document that better. (To be clear, Pako and Zlib are using the wrong naming here, not `fflate` - for some reason the Zlib C library calls the Zlib format "deflate".)

Can you try replacing your `inflateSync`/`deflateSync` calls with `unzlibSync` and `zlibSync`?

**Comment by jammerxd** [comment]
Yeah I tried that too and I got "invalid zlib data"

**Comment by jammerxd** [comment]
Nevermind - it seems that did the trick!

**Comment by 101arrowz** [comment]
Glad you got it working! For anyone else who finds this issue, I think I saw the encoding issue you were talking about - your Base64 strings weren't being encoded/decoded properly. `atob` returns a binary string, so you need to run `fflate.strToU8(btoa(data), true)` to decode Base64 to a Uint8Array. Similarly, to encode the `fflate` output to Base64 you should do `btoa(fflate.strFromU8(compressed, true))`.

**Comment by jammerxd** [comment]
To be clear - yeah that's exactly what the issue was.

What I ended up with on the javascript side:

To Send A Compressed Message:
```
            const buff = fflate.strToU8(message);
            const compressed = fflate.zlibSync(buff);
            const data = btoa(fflate.strFromU8(compressed,true));
            this.#ws.send(data);
```

To Receive A Compressed Message:
```
        const buff = fflate.strToU8(atob(event.data),true);
        const decompressed = fflate.unzlibSync(buff);
        const data = fflate.strFromU8(decompressed);
```

On the C++ Side:
To Send A Compressed Message:
```
                Compression::Zlib::Compress(*message);
		message->ToBase64();
```
To Receive A Compressed Message:
```
	Compression::Binary_Data_T msg = Compression::Binary_Data_T();
	msg.Append(data);
	msg.FromBase64();
	Compression::Zlib::Decompress(msg);
	data.clear();
	data = msg.to_string();
```
