### ISSUE TITLE
CDN bundle for 0.8.1 is broken

### ISSUE THREAD

**Issue by mydea** [101arrowz/fflate#189]
I just noticed that this:

https://cdn.jsdelivr.net/npm/fflate@0.8.1/umd/index.min.js

Does not seem to work. whereas https://cdn.jsdelivr.net/npm/fflate@0.8.0/umd/index.min.js does work! So it seems something in 0.8.1 is tripping up there 🤔 not a big deal but though I'd let you know!

**Comment by 101arrowz** [comment]
That's annoying. I don't know if there's any way to get the CDNs to take down that version, or at least have the default page redirect to v0.8.0 for now. Thanks for letting me know, I'll fix this for v0.8.2.

**Comment by 101arrowz** [comment]
Fixed in v0.8.2, thanks for reporting!
