### ISSUE TITLE
fflate.decompressSync is not a function when using `nifti-reader-js` (React)

### ISSUE THREAD

**Issue by pcanas** [101arrowz/fflate#193]
**How to reproduce**
1. Clone this repo: https://github.com/Chesneynl/nifti-loader-with-error
2. `yarn install`
3. `yarn dev`

`package.json` dependencies are
```
    "fflate": "^0.8.1",
    "nifti-reader-js": "^0.6.8",
```

**The problem**

We get an error because the fflate functions are not found

<img width="1344" alt="Captura de pantalla 2023-12-07 a las 19 23 13" src="https://github.com/101arrowz/fflate/assets/32467089/decdd94a-1746-4532-a779-1951f26ae3a1">

<img width="748" alt="Captura de pantalla 2023-12-07 a las 19 24 11" src="https://github.com/101arrowz/fflate/assets/32467089/b0df191b-a9a4-4185-b3fb-fdb308061396">

These are found when I am navigating my project, so it might have to do with the bundling...

**Comment by 101arrowz** [comment]
This is most likely an issue with the bundler. Webpack's tree shaking has always been a bit suspicious - I'll look into what specifically is causing this.

**Comment by pcanas** [comment]
@101arrowz any updates?

**Comment by 101arrowz** [comment]
This will take me a few more weeks to get to, sorry for the delay!

**Comment by gosvig123** [comment]
@101arrowz , thanks for looking into this and happy new year.
Just wanted to check in to see if you had any more context on this?

**Comment by pcanas** [comment]
> This will take me a few more weeks to get to, sorry for the delay!

@101arrowz Hi, any updates? Thanks!

**Comment by 101arrowz** [comment]
Looking into it now. This seems like a Webpack misconfiguration; the `require("fflate")` call in `nifti.js` is somehow resolving to a URL in the build. I'll look into this further to see if this is something that can be easily fixed.
