### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by realrecordzLab** [101arrowz/fflate#20]
I have a working browser extension that use JSZip to create and read zip files. I want to migrate it to fflate but I have a problem while I'm trying to implement the library. I get this error inside the console `Uncaught RangeError: Maximum call stack size exceeded` when I try to create a zip file that will include multiple files. While in JSZip I was able to add each single file to an archive using the `zip.file()` function, it's not clear for me how I can proceed with this library. At the moment I have this code in my vue methods
```
processFiles() {
      this.isProcessing = true;
// this.files is an array that hold dropped files from the user that are in the e.dataTransfer.files 
      this.files.forEach( (f) => {
        let filename = f.name
        zip({filename: f},{consume: true, level: 9, mem: 12}, (err, data) => {
          if(err){ 
            console.log(err);
            return;
          }
          console.log(data);
        });
      });
}
```
As you can see I need to loop an array of files and add each file to the archive before give it to the user. I'm using the async api, Is possible to have an example of how to manage this?

**Comment by pippo111** [comment]
Check out demo site: https://101arrowz.github.io/fflate/

You cannot add `File` object directly, you have to read file buffer. This is example with Promise, so you can easily use it with async/await:

```
function readFile(file: File) {
  return new Promise<Uint8Array>((resolve, reject) => {
    const reader = new FileReader();

    reader.onloadend = () => {
      resolve(new Uint8Array(reader.result as ArrayBuffer));
    };
    reader.onerror = reject;
    reader.readAsArrayBuffer(file);
  });
}
```

Then you have to create archive structure, for example:
```
const archiveStruct: any = {}
for (const file of files) {
    const fileBuffer = await readFile(file);
    archiveStruct[file.name] = fileBuffer;
}
```

Then you can zip all files, like so:
```
fflate.zip(
      archiveStruct,
      { consume: true, level: 9 },
      (err, out) => {
        if (err) {
          console.log("error", err);
          return;
        }

        console.log(out); // this is your archive buffer
      }
);
````

**Comment by realrecordzLab** [comment]
Ok, thank you. I will give it a try. At the moment I've tried also with file reader but the resulting archive was always 22kb and empty. I will let you know if the issue is solved

**Comment by realrecordzLab** [comment]
> archiveStruct[file.name] = fileBuffer;

I've modified a bit the code because I'm not using typescript but it seems working fine. I've created a method to read each single file and replaced the `forEach()` loop with `for()` as you have suggested. Just the last thing, I need to read the file also if I want to unzip it's content?

**Comment by realrecordzLab** [comment]
> Check out demo site: https://101arrowz.github.io/fflate/
> 
> You cannot add `File` object directly, you have to read files first. This is example with `Promise`, so you can easily use it with async/await:
> 
> ```
> function readFile(file: File) {
>   return new Promise<Uint8Array>((resolve, reject) => {
>     const reader = new FileReader();
> 
>     reader.onloadend = () => {
>       resolve(new Uint8Array(reader.result as ArrayBuffer));
>     };
>     reader.onerror = reject;
>     reader.readAsArrayBuffer(file);
>   });
> }
> ```
> 
> Then you have to create archive structure, for example:
> 
> ```
> const archiveStruct: any = {}
> for (const file of files) {
>     const fileBuffer = await readFile(file);
>     archiveStruct[file.name] = fileBuffer;
> }
> ```
> 
> Then you can zip all files, like so:
> 
> ```
> fflate.zip(
>       archiveStruct,
>       { consume: true, level: 9 },
>       (err, out) => {
>         if (err) {
>           console.log("error", err);
>           return;
>         }
> 
>         console.log(out); // this is your archive buffer
>       }
> );
> ```

I've modified a bit the code because I'm not using typescript but it seems working fine. I've created a method to read each single file and replaced the forEach() loop with for() as you have suggested. Just the last thing, I need to read the file also if I want to unzip it's content?
