### ISSUE TITLE
unzip: RangeError: Invalid typed array length

### ISSUE THREAD

**Issue by chambo-e** [101arrowz/fflate#23]
Hello, when I try to unzip a zip made with `zip` I have this error

```
RangeError: Invalid typed array length: -48783
```

Codesandbox with reproduction:
https://codesandbox.io/s/friendly-kare-dgcls

This happens on Chrome, does not seems to throw an error on Safari but doesn't work either

Might be related with #21 but I don't use any stream

Also I'm using v0.4.7 

Thanks in advance :)

**Comment by 101arrowz** [comment]
I checked the CodeSandbox, but there were two mistakes with the code you used:
1. You tried to use `strToU8` on binary string data without the second argument being `true`. You can either use `strToU8(data, true)`, or you can fetch as an ArrayBuffer and use `new Uint8Array(data)`, which is much more efficient.
2. You tried to run `strFromU8` on the unzipped structure, but you need to run it on a single Uint8Array. The directory structure looks like this: `{ file1: Uint8Array(50) [...], file2: Uint8Array(200000) [...] }`. I saw that you had a `handler.js`, so you can run `strFromU8` on `unzipped['handler.js']`.

Corrected sandbox: https://codesandbox.io/s/jovial-poincare-2fhk7?file=/src/index.js

**Comment by chambo-e** [comment]
Thanks a lot for the quick answer and the tip 👍 

If I can bother you just a little bit more (and satisfy my curiosity):
```js
    const { data } = await axios.get("https://test.scw.company/toto.zip");
    const buffer = new strToU8(data, true);
```

while inefficient is supposed to be equal to, right ?
```js
    const { data } = await axios.get("https://test.scw.company/toto.zip", {
      responseType: "arraybuffer"
    });
    const buffer = new Uint8Array(data);
```

But I feel like it cannot find the "handler.js" file in the unzipped structure (https://codesandbox.io/s/dry-star-tbvu3)

Happy new year btw 🎉

**Comment by 101arrowz** [comment]
I guess Axios is encoding the data incorrectly. That may be an issue with XHR or Axios itself, but the binary string method is so incredibly bad for performance and memory that I'd hope it would never be necessary, so I'm probably not going to look into the issue further. Specifically, binary string decoding is about 5ms/MB and takes 2x more memory than the raw binary; after converting to Uint8Array, 3x more. The main reason binary string support exists is to support legacy code.

Thanks for the issue! I wish you the best in this new year as well!
