### ISSUE TITLE
Can't find variable: Worker

### ISSUE THREAD

**Issue by felixmariotto** [101arrowz/fflate#33]
In Webkit ( I tried both Safari macOS and Safari iOS ) an error is thrown when I call `fflate.unzip` in a web worker : 
`ReferenceError: can't find variable: Worker`

This is where it comes from : 
https://github.com/101arrowz/fflate/blob/7471ec9e4c6a05d665d153b8361a5e29ad16f257/src/node-worker.ts#L11

to be accurate I bundle with Webpack, I import `unzip` like so :
```javascript
import { unzip } from 'fflate'
```
and then I use it in this function : 
```javascript
unzip( new Uint8Array( buffer ), (err, unzipped) => {

	if ( err ) reject( err );

	resolve( unzipped.f1 );

});
```

Everything works like a charm in Chrome and Chrome for Android ( congrats for your work by the way ).
I tried with different files, big and small ( 1.5Mb to >300Mb ).

I believe this error occurs because Webkit doesn's support creating new web workers from inside web workers. I found a thread [here](https://stackoverflow.com/questions/64045547/javascript-referenceerror-cant-find-variable-worker-in-safari-when-creating) with some vague  references.

I need to unzip the file inside my own worker because I'm doing other expensive things after unzipping, it would not make sense to message this big buffer back and forth the main thread uselessly.

It's possible that I didn't understand how to use your library, and I should use another method to get this done. In that case can you give me a hint please ? My zipped files are compressed with `fflate.zip` ( in nodejs ).

possibly related: #11

**Comment by felixmariotto** [comment]
So I re-read the doc and found that the async methods are not spawning any web worker, so I changed my function to this : 

```javascript
function unzipBuffer( buffer ) {

	return new Promise( (resolve, reject) => {

		const decompressed = fflate.unzipSync( new Uint8Array( buffer ) );

		resolve( decompressed.f1 );

	});

}
```

And it fixed it.

I think you should tidy up a bit your documentation... At the moment, crawling through the readme to find some clue is really a pain. Use Github Wiki, it's easy to setup and you can like the different pages of your wiki in the readme.

**Comment by 101arrowz** [comment]
Actually, `unzip` does spawn a web worker. You shouldn't use `fflate`'s async methods in a web worker for this reason. Might as well use the sync version if you are already off the UI thread.

Yes, documentation isn't great, I'll try to fix that soon. The Wiki already has a few pages and I'm looking to add more soon.
