### ISSUE TITLE
ESM import no longer works in 0.5.3

### ISSUE THREAD

**Issue by eevee** [101arrowz/fflate#36]
Not sure if this was _intended_, but I've been doing:

```
import * as fflate from 'https://unpkg.com/fflate/esm/index.mjs';
```

As of 0.5.3, this fails, because the following code at the top of `index.mjs`:

```
try {
    Worker = /*#__PURE__*/ require('worker_threads').Worker;
}
catch (e) {
}
```

has moved to `node-worker.js` and been replaced with:

```
import wk from './node-worker.js';
```

which doesn't work in a browser because `node-worker.js` doesn't define a default export, or any exports at all.

**Comment by 101arrowz** [comment]
Indeed, you're importing the wrong file. I made the change specifically to enforce correct imports. Instead of importing `/esm/index.mjs`, try `/esm/browser.js`.

**Comment by eevee** [comment]
Thanks; I went for the `.mjs` because of the extension, since the docs didn't say much either way.  (I don't currently have any build step at all, and since fflate is my first dependency I wasn't in a huge hurry to add one.)
