### ISSUE TITLE
Feature request: Shared context

### ISSUE THREAD

**Issue by intrnl** [101arrowz/fflate#5]
It would be nice to have the ability to create shared context/sliding window

```
let inflate = new Inflate({ chunkSize: 128 * 1024 })

inflate.push(chunk)
inflate.push(chunk, Z_SYNC_FLUSH)

console.log(inflate.result.toString())
```

**Comment by 101arrowz** [comment]
This would require a rewrite of a lot of the core functionality, so I'm not sure how feasible getting this done will be. However, I'll see what I can do.

**Comment by 101arrowz** [comment]
I have a pretty good solution in mind for compression streams, but decompression may be a bit sketchy. I'll add this after ZIP support

**Comment by 101arrowz** [comment]
After looking into this some more, there are two problems with this suggestion:
1. The output is still stored in full in memory. Any memory savings are lost as a result.
2. The synchronous access to the result means the decompression must be synchronous, losing any performance benefits.
However, I do plan to implement an asynchronous duplex-stream version of this.

**Comment by 101arrowz** [comment]
Update, I've added support for synchronous duplex inflate streams, which I know is by far the hardest part. Performance could be better, so I'll work on that before adding asynchronous streams, deflate streams (very simple), and ushing the changes.

**Comment by 101arrowz** [comment]
Fixed performance! Main culprit was the new error-checking taking extra time, but instead of removing it I just optimized some other areas. I've also added synchronous deflate streams. I'm going to finish up by fixing the workers and everything should be fine from there.

**Comment by 101arrowz** [comment]
This issue is now complete as of 575f8d6a82b8d31558a9d6cf9307612fbb516e4b. Thanks for the feature request!
