### ISSUE TITLE
Unstable. Freeze on simple input

### ISSUE THREAD

**Issue by eXponenta** [101arrowz/fflate#6]
**Test:**
https://codesandbox.io/s/sweet-ritchie-g49rw?file=/src/index.js

Encoding - zlib deflate

**Actual:** inifinity loop inside decoding phase
**Expected:** faster that pako

**Comment by 101arrowz** [comment]
Could you link me the file that `test.bin`? I'd like to test locally.

**Comment by 101arrowz** [comment]
The issue is that you're just converting Base64 data into a Uint8Array without using `btoa` on it first. If you `btoa`, then run `decompress`, it will work.

**Comment by 101arrowz** [comment]
Found the issue and fixed it. Will update soon.
