### ISSUE TITLE
Support Promises out of the box

### ISSUE THREAD

**Issue by brettz9** [101arrowz/fflate#70]
**What can't you do right now?**

Use the async methods as promises without using promisify (and for the browser, needing to bundle or otherwise add a promisfy utility).

**An optimal solution**

Be able to use the async methods as promises.

**(How) is this done by other libraries?**

[JSZip](https://stuk.github.io/jszip/) appears to support promises, but not the other libraries.

Thanks!

**Comment by 101arrowz** [comment]
This was an intentional design decision to support older browsers without a polyfill. However, writing a `promisify` yourself is trivial:

```js
const promisify = func => (...args) => {
  return new Promise ((resolve, reject) =>
    func.call(null, ...args, (err, res) => err
      ? reject(err)
      : resolve(res)
    )
  );
}
```

I was thinking of creating a version of `fflate` with modern features such as Promise, WHATWG streams, etc. I'll let you know if that happens.
