### ISSUE TITLE
Feature request: Progress callback

### ISSUE THREAD

**Issue by sHoskens** [101arrowz/fflate#8]
It would be great to have some sort of progress callback which could give an estimated percentage of the completed work. Am willing to help out with this feature if you can point me in the right direction. :)

**Comment by 101arrowz** [comment]
Ah, so like JSZip. This would be quite simple for ZIP files but potentially more difficult for raw compression/decompression. Which one are you looking for?

**Comment by sHoskens** [comment]
I'm currently using your gzip function, so I suppose that's ZIP? :)

**Comment by 101arrowz** [comment]
No, there's an API for creating multi-file ZIP archives, which can be placed into a file called `something.zip` to get all of the source files out. That's `zip(Sync)` and `unzip(Sync)`. What you're referring to is GZIP, which is a wrapper for raw compression.

Adding support for progress markers may be difficult but should be possible. However, it may not be worth the massive bundle size increase that it will likely take. Instead, I'm going to finish working on a streaming version of the compression APIs, so you can send small portions of the data at a time, and when they complete you can update your progress by dividing the chunk number by the total chunk count.

**Comment by sHoskens** [comment]
That would be perfect, yes. I'm actually doing a similar thing right now with pako inside a custom webworker, so what you describe there would be a major step up. Thanks, and let me know if I can help anywhere! Would not mind learning a bit more about compression.

**Comment by 101arrowz** [comment]
Alright, I'll see what I can do. If you're switching over from pako, note that there's not much reason to use fflate in a worker, since it already automatically uses highly optimized workers for the asynchronous APIs.

If you want to learn some more about DEFLATE compression, you can read [this guide](https://gist.github.com/101arrowz/253f31eb5abc3d9275ab943003ffecad), especially the RFCs it mentions. More modern compression techniques, such as [zstd](https://tools.ietf.org/html/rfc8478), exist, but DEFLATE is universally understood and is the basis of most modern techniques as well.

**Comment by sHoskens** [comment]
Yes, I noticed that in your documentation, and indeed doing it outside of the worker. Much easier, I like fflate already.

And thanks a lot for those guides, will take a look at that!

**Comment by 101arrowz** [comment]
I'm going to leave this issue open until I fix it, but please see #5 for updates.

**Comment by 101arrowz** [comment]
As mentioned in #5, this issue is now fixed as of 575f8d6. Thanks for the feature request!

**Comment by Clopma** [comment]
I'm not sure this feature has been implemented. Sure you can chunk the file, push all the chunks and wait for the callback, but I was hoping there's some way to use let's say the .zip method and just have some sort of feedback.

**Comment by aadarshkt** [comment]
Is there any option to track compression and decompression progress tracking available now with fflate.gunzip()
