### ISSUE TITLE
JS file

### ISSUE THREAD

**Issue by photopea** [101arrowz/fflate#97]
Hi, could you provide a JS file of this library? Is this library open-source? I do not use NPM.

**Comment by photopea** [comment]
I tried to inflate a 192 MB file.

fflate.unzlibSync took 6075 ms
pako.inflateRaw took 5563 ms
UZIP.inflateRaw took 4379 ms

Is there a method in "fflate" similar to "inflateRaw", which does not check the CRC, so that it could be faster? Also, could you provide the same interface ask pako and UZIP, so that we can just replace "pako" with "fflate" in the code to switch to your library?

**Comment by 101arrowz** [comment]
Actually unzlibSync ignores the CRC, could you send this file with bad performance so I can investigate?

**Comment by photopea** [comment]
It is about 5% faster when I add the output as a second agrugment.  I was not able to find any description of unzlibSync , do you have a manual somewhere?

It happened for a larege PSD file, which contains ZLIB streams inside. Raster image (a photo) is being compressed, the output is about 2x smaller than the input. I think fflate should be slower even for other similar cases.

**Comment by photopea** [comment]
Ok, here it is
[data.txt](https://github.com/101arrowz/fflate/files/7464037/data.txt)

**Comment by photopea** [comment]
This is the input for pako.inflateRaw and UZIP.inflateRaw.

**Comment by 101arrowz** [comment]
On my computer, `fflate.inflateSync` decompresses that file in ~270ms average, `UZIP.inflateRaw` decompresses in ~260ms average, `pako.inflateRaw` decompresses in ~300ms average. If `fflate` is slower than Pako on your machine for this file, I'm interested to know what CPU and platform you're using. I'm running on Node.js in WSL with an i7-8650U laptop.

**Comment by photopea** [comment]
Can you run it 20 times in a row? Maybe a browser optimizes the code, if it is executed a lot.

**Comment by 101arrowz** [comment]
I took the average of 30 runs for those measurements. The cold start time is the main difference maker for the averages: Pako has pretty poor performance before JIT optimization (~450ms for the first few iterations) but becomes around 270ms after. `fflate` starts at ~350ms and goes to 250ms, UZIP starts at 300ms and goes to 250ms.

**Comment by photopea** [comment]
I mean measuring a total time for 20 runs. That is what my program does. It performs a decompression of about 20 parts (20x7 MB), I want to make the total time as low as possible.

**Comment by 101arrowz** [comment]
Well to get the total time you can multiply average by number of runs. So for Pako its 9000ms, `fflate` is 8100ms, UZIP is 7800ms.

**Comment by photopea** [comment]
The first run takes longer than the 20th run. After several runs, next runs take the identical time. So it is not clear what you mean by "average". In my case, I was testing a total time for the first 20 runs.

**Comment by 101arrowz** [comment]
Average is the mean, i.e. the total time for all runs divided by the number of runs. So multiplying the mean by the number of runs gives the total time for all runs.

**Comment by 101arrowz** [comment]
Closed because I'm not sure if there's anything actionable on this issue but let me know if you have further questions.
