### ISSUE TITLE
CRC fails for streaming ZIP file if compression level set to 0

### ISSUE THREAD

**Issue by harveylee** [101arrowz/fflate#98]
**How to reproduce**
Zip the attached `truck.jpg` using the streaming ZIP interface with level set to 0. Try to extract it again using an off-the-shelf ZIP program.

```
// Node 14.15.4
import fs from 'fs'
import { Zip, AsyncZipDeflate } from 'fflate'

const buf = fs.readFileSync('truck.jpg')
const writeStream = fs.createWriteStream('truck.zip')
const zip = new Zip((err, data, final) => {
  if (err !== null) throw err
  writeStream.write(data)
  if (final) writeStream.end()
})

const file = new AsyncZipDeflate('truck.jpg', { level: 0 })
zip.add(file)
file.push(buf, true)
zip.end()
```

**The problem**
Both Windows Explorer and 7-ZIP reports a CRC error when trying to extract truck.jpg from the ZIP file. This doesn't seem to occur using the `zip()` interface nor at compression levels other than 0 (tried 1, 2, 6, 9). Also other files seem to work, there's something specific about this file and others.

![truck](https://user-images.githubusercontent.com/5846733/139625532-a1abe891-4fc1-4d20-a148-3103abd6af47.jpg)

**Comment by 101arrowz** [comment]
Thanks for the bug report, I'll look into this in a few days.

**Comment by 101arrowz** [comment]
Haven't gotten a chance to check this out yet, but I should have time this weekend, sorry for the delay.

**Comment by harveylee** [comment]
If it helps, I switched to using `zip()` for now, which doesn't seem to suffer from this problem?

i.e. this
```js
import { zip } from 'fflate'
zip({ ... }, (err, data) => { ... })
```

I also recall running into some (related?) issues at other compression levels with other files, but I forgot to keep notes.

**Comment by 101arrowz** [comment]
You mentioned it in your original issue, but it's kind of weird because `zip` and `Zip` call the same CRC function internally.

**Comment by 101arrowz** [comment]
I've finally been able to reproduce this error and will fix it as soon as possible.
